# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m venv venv
    venv/bin/python -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    bash ./scripts/test.sh all
  displayName: 'Run tests'

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: $(KNOWN_HOSTS)
    sshKeySecureFile: '2105-may24-devops-ubuntu-vm-1_key.pem'

- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: './ansible/check-installs.yml'
    inventoriesAgentMachine: 'file'
    inventoryFileOnAgentMachine: './ansible/inventory'
  displayName: 'Ansible- Check Installs'

- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: './ansible/install.yml'
    inventoriesAgentMachine: 'file'
    inventoryFileOnAgentMachine: './ansible/inventory'
  displayName: 'Ansible- Install'

- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: './ansible/test.yml'
    inventoriesAgentMachine: 'file'
    inventoryFileOnAgentMachine: './ansible/inventory'
  displayName: 'Ansible- Test'