- name: Install David R's P0
  hosts: all
  vars:
      app_path: "~/ansible-repos/davidr-project0"
  tasks:
    - name: Clone git
      git:
        repo: https://github.com/2105-may24-devops/davidr-project0
        clone: yes
        force: yes
        dest: "{{ app_path }}"
      
    - name: Install setuptools via pip
      pip:
        name: setuptools
        executable: pip3
      become: yes
      become_user: root

    - name: Install virtualenv via pip
      pip:
        name: virtualenv
        executable: pip3
      become: yes
      become_user: root

    - name: Install requirements in venv
      pip:
        requirements: "{{ app_path }}/requirements.txt"
        virtualenv: "{{ app_path }}/venv"
        virtualenv_python: python3

    - name: Create a directory if it does not exist
      file:
        path: "{{ app_path }}/saves/"
        state: directory


    - name: Creating a save directory and file
      copy:
        force: yes
        dest: "{{ app_path }}/saves/save1.json"
        content: |
          [
            {
                "py/object": "entity.Player",
                "name": "Ansible",
                "level": 150,
                "health": 100,
                "stats": {
                    "py/object": "entity.Stats",
                    "attack": 5,
                    "defense": 4,
                    "dexterity": 3,
                    "evasion": 20
                },
                "is_guarding": false,
                "equipped": {
                    "weapon": null,
                    "armor": null,
                    "shield": null
                },
                "inventory": [
                    {
                        "py/object": "entity.Item",
                        "name": "Potion",
                        "health": 10,
                        "stats": {
                            "py/object": "entity.Stats",
                            "attack": 0,
                            "defense": 0,
                            "dexterity": 0,
                            "evasion": 0
                        }
                    }
                ]
            },
            {
                "py/object": "game_manager.Config",
                "enemy_names": [
                    "Dragon",
                    "Orc",
                    "Mage"
                ],
                "distance": 20,
                "chance_of_encounter": 0.4,
                "chance_of_battle": 0.8,
                "walking_speed": 0.5
            }
          ]
