- name: Test David R's P0
  hosts: all
  vars:
      app_path: "~/ansible-repos/davidr-project0"
  tasks:
    - name: Make test executable
      file:
        path: "{{ app_path }}/scripts/test.sh"
        mode: a+x
    - name: Test the project
      shell:
        cmd: |
          ./scripts/test.sh all
        chdir: /home/davidr/ansible-repos/davidr-project0
